from .checkerboard import Checkerboard
from .striped import Striped
from .star import Star
from .radial import Radial
from .spiral import Spiral
from .diagonal_stripes import DiagonalStripes
from .smiley import Smiley
from .triangle import Triangle
from .hourglass import Hourglass
from .square import Square